"""initial schema

Revision ID: 1ad4857436af
Revises:
Create Date: 2026-03-30 18:08:42.526399

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ad4857436af"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hourly_rate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "actual_availability_percentage", sa.Integer(), server_default="100", nullable=False
        ),
        sa.Column(
            "target_utilization_percentage", sa.Integer(), server_default="100", nullable=False
        ),
        sa.Column("status", sa.String(length=50), server_default="active", nullable=False),
        sa.Column("department", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actual_availability_percentage >= 0 AND actual_availability_percentage <= 100",
            name="ck_employees_actual_availability",
        ),
        sa.CheckConstraint(
            "target_utilization_percentage >= 0 AND target_utilization_percentage <= 100",
            name="ck_employees_target_utilization",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=50), server_default="planning", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("end_date >= start_date", name="ck_projects_dates"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), server_default="viewer", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "project_phases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "allocation_type", sa.String(length=50), server_default="headcount", nullable=False
        ),
        sa.Column("required_hours", sa.Integer(), nullable=True),
        sa.Column("required_headcount", sa.Integer(), nullable=True),
        sa.Column("phase_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("end_date >= start_date", name="ck_phases_dates"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_project_phases_project_id", "project_phases", ["project_id"], unique=False)
    op.create_table(
        "project_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("phase_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column(
            "allocation_type", sa.String(length=50), server_default="percentage", nullable=False
        ),
        sa.Column("allocated_hours", sa.Integer(), nullable=True),
        sa.Column("allocation_percentage", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "allocated_hours IS NULL OR allocated_hours > 0", name="ck_assignments_hours"
        ),
        sa.CheckConstraint(
            "allocation_percentage IS NULL OR "
            "(allocation_percentage >= 1 AND allocation_percentage <= 100)",
            name="ck_assignments_percentage",
        ),
        sa.CheckConstraint("end_date >= start_date", name="ck_assignments_dates"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["phase_id"], ["project_phases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_assignments_dates", "project_assignments", ["start_date", "end_date"], unique=False
    )
    op.create_index(
        "idx_assignments_employee_id", "project_assignments", ["employee_id"], unique=False
    )
    op.create_index("idx_assignments_phase_id", "project_assignments", ["phase_id"], unique=False)
    op.create_index(
        "idx_assignments_project_id", "project_assignments", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_assignments_project_id", table_name="project_assignments")
    op.drop_index("idx_assignments_phase_id", table_name="project_assignments")
    op.drop_index("idx_assignments_employee_id", table_name="project_assignments")
    op.drop_index("idx_assignments_dates", table_name="project_assignments")
    op.drop_table("project_assignments")
    op.drop_index("idx_project_phases_project_id", table_name="project_phases")
    op.drop_table("project_phases")
    op.drop_table("users")
    op.drop_table("projects")
    op.drop_table("employees")
    # ### end Alembic commands ###
