"""add_employee_role_optional_enddate_budget_settings_role_requirements

Revision ID: 5800ea4c4e71
Revises: 1ad4857436af
Create Date: 2026-03-30 20:49:13.249738

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5800ea4c4e71"
down_revision: Union[str, Sequence[str], None] = "1ad4857436af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hours_per_full_time", sa.Integer(), server_default="176", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("hours_per_full_time > 0", name="ck_settings_hours_positive"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role_requirements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("phase_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("allocation_percentage", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "allocation_percentage >= 1 AND allocation_percentage <= 100",
            name="ck_role_req_percentage",
        ),
        sa.CheckConstraint("count >= 1", name="ck_role_req_count"),
        sa.ForeignKeyConstraint(["phase_id"], ["project_phases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_role_requirements_phase_id", "role_requirements", ["phase_id"], unique=False
    )
    op.create_index(
        "idx_role_requirements_project_id", "role_requirements", ["project_id"], unique=False
    )
    op.add_column(
        "employees",
        sa.Column("role", sa.String(length=50), server_default="developer", nullable=False),
    )
    op.add_column(
        "project_phases", sa.Column("budget", sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.alter_column("projects", "end_date", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "end_date", existing_type=sa.DATE(), nullable=False)
    op.drop_column("project_phases", "budget")
    op.drop_column("employees", "role")
    op.drop_index("idx_role_requirements_project_id", table_name="role_requirements")
    op.drop_index("idx_role_requirements_phase_id", table_name="role_requirements")
    op.drop_table("role_requirements")
    op.drop_table("global_settings")
    # ### end Alembic commands ###
